# Generated by Django 3.1.7 on 2021-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Electronic', 'Electronic'), ('Books', 'Books')], default='Gen', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
