# Generated by Django 3.1.7 on 2021-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
